export const FollowupOptions = [
  {
    label:'Select',
    type:'checkbox',
    recordName: '',
    width: '24',
    sort: false,
  },
  // {
  //   label:'Coordinator',
  //   type:'people',
  //   recordName: 'coordinator',
  //   people: [],
  //   width: '56',
  //   sort: false,
  // },
  {
    label:'Old Claim Id',
    type:'text',
    recordName: 'claim_id',
    width: '52',
    sort: false,
  },
  {
    label:'New Claim Id',
    type:'text',
    recordName: 'new_claim_id',
    width: '52',
    sort: false,
  },
  {
    label:'In Collab',
    type:'text',
    recordName: 'claim_status',
    width: '52',
    sort: false,
  },
  {
    label:'Name',
    type:'text',
    recordName: 'name',
    width: '52',
    sort: true,
  },
  {
    label:'DOB',
    type:'text',
    recordName: 'dob',
    width: '52',
    sort: false,
  },
  {
    label:'Policy',
    type:'text',
    recordName: 'policy_id',
    width: '52',
    sort: false,
  },
  {
    label:'Insruance',
    type:'text',
    recordName: 'insurance',
    width: '96',
    sort: true,
  },
  {
    label:'Facility',
    type:'text',
    recordName: 'facility',
    width: '52',
    sort: false,
  },
  {
    label:'Network',
    type:'text',
    recordName: 'network',
    width: '52',
    sort: false,
  },
  {
    label:'Status',
    type:'text',
    recordName: 'status',
    width: '96',
    sort: false,
  },
  {
    label:'Notes',
    type:'note',
    recordName: 'fu_note',
    width: '80',
    sort: false,
  },
  {
    label:'Charged Total',
    type:'dollar',
    recordName: 'charged_total',
    width: '52',
    sort: false,
  },
  {
    label:'Paid Total',
    type:'dollar',
    recordName: 'paid_total',
    width: '52',
    sort: true,
  },
  {
    label:'Payout %',
    type:'percent',
    recordName: 'payout_ratio',
    width: '52',
    sort: true,
  },
  {
    label:'Balance Total',
    type:'dollar',
    recordName: 'balance_total',
    width: '52',
    sort: false,
  },
  {
    label:'Start Date',
    type:'date',
    recordName: 'start_date',
    width: '52',
    sort: false,
  },
  {
    label:'End Date',
    type:'date',
    recordName: 'end_date',
    width: '52',
    sort: true,
  },
  {
    label:'Delete',
    type:'delete',
    recordName: '',
    width: '52',
    sort: false,
  },
]